;;; 04-make-account.scm

(define (make-account balance password)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                   balance)
            "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount))
        balance)
    (define (call-the-cops)
        (error "You try too much times, calling the cops..."))
    (let ((tried-times 0)
          (max-try-times 7))
        (define (dispatch input-password mode)
            (if (eq? password input-password)
                (begin
                    (set! tried-times 0)
                    (cond ((eq? mode 'withdraw) withdraw)
                          ((eq? mode 'deposit) deposit)
                          (else (error "Unknown request -- MAKE-ACCOUNT" mode))))
                (begin
                    (set! tried-times (+ tried-times 1))
                    (lambda (input-whatever)
                        (if (= tried-times max-try-times)
                            (call-the-cops)
                            "Incorrect password")))))
        dispatch))
